#!/usr/bin/perl -w -- 
# generated by wxGlade 0.6.1 on Sat Nov 10 10:47:40 2007
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
1;

package main;

use Glade::Browser;


unless(caller){
	local *Wx::App::OnInit = sub{1};
	my $app = Wx::App->new();
	Wx::InitAllImageHandlers();

	my $frame_1 = Glade::Browser->new();

	$app->SetTopWindow($frame_1);
	$frame_1->Show(1);
	$app->MainLoop();
}
