# generated by wxGlade 0.6.1 on Sat Nov 10 13:34:08 2007
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
package Glade::Browser;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

# begin wxGlade: ::dependencies
# end wxGlade

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: Glade::Browser::new

	$style = wxDEFAULT_FRAME_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{window_1} = Wx::SplitterWindow->new($self, -1, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_BORDER);
	$self->{window_1_pane_2} = Wx::Panel->new($self->{window_1}, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{window_1_pane_1} = Wx::Panel->new($self->{window_1}, -1, wxDefaultPosition, wxDefaultSize, );
	

	# Menu Bar

	$self->{frame_1_menubar} = Wx::MenuBar->new();
	my $wxglade_tmp_menu;
	$wxglade_tmp_menu = Wx::Menu->new();
	$self->{new_folder} = $wxglade_tmp_menu->Append(Wx::NewId(), "New folder ..", "");
	$wxglade_tmp_menu->Append(wxID_EXIT, "Exit", "");
	$self->{frame_1_menubar}->Append($wxglade_tmp_menu, "File");
	$wxglade_tmp_menu = Wx::Menu->new();
	$wxglade_tmp_menu->Append(wxID_ABOUT, "About ..", "");
	$self->{frame_1_menubar}->Append($wxglade_tmp_menu, "Help");
	$self->SetMenuBar($self->{frame_1_menubar});
	
# Menu Bar end

	$self->{frame_1_statusbar} = $self->CreateStatusBar(1, 0);
	$self->{folders} = Wx::TreeCtrl->new($self->{window_1_pane_1}, -1, wxDefaultPosition, wxDefaultSize, wxTR_HAS_BUTTONS|wxTR_NO_LINES|wxTR_LINES_AT_ROOT|wxTR_EDIT_LABELS|wxTR_TWIST_BUTTONS|wxTR_DEFAULT_STYLE|wxSUNKEN_BORDER);
	$self->{filez} = Wx::ListCtrl->new($self->{window_1_pane_2}, -1, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxSUNKEN_BORDER);

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: Glade::Browser::__set_properties

	$self->SetTitle("FileZ");
	$self->SetSize(Wx::Size->new(400, 300));
	$self->{frame_1_statusbar}->SetStatusWidths(-1);
	
	my( @frame_1_statusbar_fields ) = (
		"frame_1_statusbar"
	);

	if( @frame_1_statusbar_fields ) {
		$self->{frame_1_statusbar}->SetStatusText($frame_1_statusbar_fields[$_], $_) 	
		for 0 .. $#frame_1_statusbar_fields ;
	}

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: Glade::Browser::__do_layout

	$self->{sizer_1} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sizer_3} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sizer_2}->Add($self->{folders}, 1, wxEXPAND, 0);
	$self->{window_1_pane_1}->SetSizer($self->{sizer_2});
	$self->{sizer_3}->Add($self->{filez}, 1, wxEXPAND, 0);
	$self->{window_1_pane_2}->SetSizer($self->{sizer_3});
	$self->{window_1}->SplitVertically($self->{window_1_pane_1}, $self->{window_1_pane_2}, );
	$self->{sizer_1}->Add($self->{window_1}, 1, wxEXPAND, 0);
	$self->SetSizer($self->{sizer_1});
	$self->Layout();
	$self->Centre();

# end wxGlade
}

# end of class Glade::Browser

1;

